# Generated by Django 5.2.8 on 2025-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('resource_type', models.CharField(choices=[('Article', 'Article'), ('Video', 'Video')], max_length=20)),
            ],
        ),
    ]
