# Generated by Django 5.2.8 on 2025-11-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_size', models.PositiveIntegerField(default=1, help_text='Number of people in the household')),
                ('dietary_preferences', models.CharField(blank=True, help_text='e.g., Vegetarian, Vegan, Halal', max_length=200)),
                ('budget_range', models.CharField(choices=[('Low', 'Budget-Friendly'), ('Medium', 'Standard'), ('High', 'Premium')], default='Medium', max_length=100)),
                ('location', models.CharField(blank=True, help_text='City or Region', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
