# Generated by Django 5.2.8 on 2025-11-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_consumptionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('Article', 'Article'), ('Video', 'Video'), ('Recipe', 'Recipe')], max_length=20),
        ),
    ]
